### PR TITLE
Feature: Add TimePicker functionality

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
NOTE: To be fixed some of the ignored files are added because I added this functionality and used for my project so that's why I also pushed the published js files.

**Comment by JoshDSommer** [comment]
Thank you @JojiePalahang, great work! One request, could you add some test coverage for this? Once that is added we can merge this in.

**Comment by JoshDSommer** [comment]
Thank you @JojiePalahang!

**Comment by JoshDSommer** [comment]
Published in 1.1.0

**Pull request merged**
